### ISSUE TITLE
server at port 6666

### ISSUE THREAD

**Issue by sreev** [SAIC-MONTREAL/SAGE#1]
What are the instructions to setup (stream or otherwise) the server listening on port 6666 ?

**Comment by sreev** [comment]
I set up simple server that outputs a text 'example response'. I received these errors in response in sage.  What is the correct response from the server running on port 6666 ?!

`Question: Amal : Turn on the TV by the credenza.
Thought:example response
Observation: Invalid Format: Missing 'Action:' after 'Thought:
Thought:example response
Observation: Invalid Format: Missing 'Action:' after 'Thought:
`

**Comment by drivkin** [comment]
See comment at https://github.com/SAIC-MONTREAL/SAGE/issues/2
