### ISSUE TITLE
What is the correct response from the server running on port 6666

### ISSUE THREAD

**Issue by sreev** [SAIC-MONTREAL/SAGE#2]
I set up simple server that outputs a text 'example response'. I received these errors in response in sage. What is the correct response from the server running on port 6666 ?!

`Question: Amal : Turn on the TV by the credenza. Thought:example response Observation: Invalid Format: Missing 'Action:' after 'Thought: Thought:example response Observation: Invalid Format: Missing 'Action:' after 'Thought: `

**Comment by drivkin** [comment]
I believe these issues have to do with code that was not properly updated for public release, and have fixed it in https://github.com/SAIC-MONTREAL/SAGE/pull/3

Please pull and try again, I think it should work now.

**Comment by drivkin** [comment]
Closing because AFAIK it is fixed
